[main]
UPLOAD_FOLDER = "images"
VERIFICATIONS = "verifications"
TASKCSV = "csv"
SQLALCHEMY_ECHO = true

[encryption]
DEFAULT_ADMIN_PASSWORD = "password"
DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_EMAIL = "user@example.com"
SECRET_KEY = "changethiskey"
SESSION_COOKIE_SECURE = true
SESSION_COOKIE_NAME = "BikeHunt_Session"
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_DOMAIN = false
SESSION_REFRESH_EACH_REQUEST = true

[flask]
SQLALCHEMY_DATABASE_URI = "postgresql://username:password@localhost/databasename1"
DEBUG = true
